# Uses shell executor on portal.vforwater.de

# Pipeline
stages:
    - test
    - deploy

# Test vforwater-portal
vforwater-portal-test:
    stage: test
    before_script:
        # For debugging
        - pwd
        - export
    script:
        # TODO Run test script...
        - echo "Testing..."

# Deploy vforwater-portal
vforwater-portal-deploy:
    stage: deploy
    script:
        # Stop web server
        - sudo systemctl stop vfwportal
        # Move current installation to "vforwater-portal_old"
        - rm -rf /home/vfwportal/vforwater-portal_old
        - test ! -d /home/vfwportal/vforwater-portal ||
            mv /home/vfwportal/vforwater-portal
               /home/vfwportal/vforwater-portal_old
        # Copy new files and prepared "settings.py"
        - cp -r ${CI_PROJECT_DIR} /home/vfwportal/vforwater-portal
        - cp /home/vfwportal/settings.py-prod
             /home/vfwportal/vforwater-portal/heron/settings.py
        # FIXME What is this for? Needed?
        - cp /home/vfwportal/setup_python.sh
             /home/vfwportal/vforwater-portal/setup_python.sh
        # Start web server
        - sudo systemctl start vfwportal
    environment:
        name: production
        url: https://portal.vforwater.de/vfwheron/
    only:
        - master
