# Usually an image like "python:3" should be sufficient
# but we need some extra libraries to enable GIS features.
image: ubuntu:16.04

# Pipeline
stages:
    - test
    - deploy

# Test vforwater-portal
vforwater-portal-test:
    stage: test
    before_script:
        - apt-get update -qq
        # Install python3 and pip3
        - apt-get install -y -qq python3 python3-pip
        # Install geospatial libraries (https://docs.djangoproject.com/en/1.11/ref/contrib/gis/install/geolibs/)
        - apt-get install -y -qq binutils libproj-dev gdal-bin
        # Install PostgreSQL dependency TODO: needed?
    #   - apt-get install -y -qq libpq-dev
        # Install required python packages
        - pip3 install django owslib psycopg2
    script:
        - python3 manage.py migrate
        # TODO: Somehow provide DB connection!? Or just use TCP...
        - python3 manage.py test

# Deploy vforwater-portal
vforwater-portal-deploy:
    stage: deploy
    script:
        # TODO: Deploy somehow
        - echo "Deploy..."
    environment:
        name: production
        url: https://vforwater-gis.scc.kit.edu/vfwheron/
    only:
        - master
