# Generated by Django 2.2.9 on 2020-01-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps_gui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WpsResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField()),
                ('access', models.DateTimeField()),
                ('open', models.BooleanField()),
                ('link', models.CharField(max_length=1024)),
                ('wps', models.CharField(max_length=255)),
                ('inputdict', models.CharField(max_length=2048)),
            ],
        ),
    ]
