# Generated by Django 2.2.9 on 2020-01-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps_gui', '0002_wpsresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpsresults',
            name='access',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='wpsresults',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
