# Generated by Django 2.2.9 on 2020-01-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps_gui', '0003_auto_20200128_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpsresults',
            name='access',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpsresults',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
