# Generated by Django 2.2.11 on 2020-03-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wps_gui', '0004_auto_20200129_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wpsresults',
            old_name='inputdict',
            new_name='inputs',
        ),
        migrations.RenameField(
            model_name='wpsresults',
            old_name='link',
            new_name='outputs',
        ),
    ]
