[renderd]
socketname=/var/run/renderd/renderd.sock
num_threads=4
tile_dir=/var/lib/mod_tile
stats_file=/var/run/renderd/renderd.stats

[mapnik]
plugins_dir=/usr/lib/mapnik/3.0/input
font_dir=/usr/share/fonts/truetype/ttf-dejavu
font_dir_recurse=0

[default]
URI=/osm/
TILEDIR=/var/lib/mod_tile
XML=/usr/share/openstreetmap-carto/style.xml
HOST=localhost
TILESIZE=256
