[program:postgresql]
command=/usr/lib/postgresql/9.5/bin/postgres -D /etc/postgresql/9.5/main
user=postgres
priority=100

[program:renderd]
command=/usr/local/bin/renderd -f -c /usr/local/etc/renderd.conf
user=osm
priority=200

[program:apache]
command=/usr/sbin/apache2ctl -D FOREGROUND
;user=www-data
priority=300
stopasgroup=true
killasgroup=true
