[program:postgresql]
command=/usr/lib/postgresql/9.5/bin/postgres -D /etc/postgresql/9.5/main
user=postgres
priority=100
stopsignal=INT

[program:renderd]
command=/bin/bash -c "sleep 5;/usr/local/bin/renderd -f -c /usr/local/etc/renderd.conf"
user=osm
priority=200

[program:apache]
command=/usr/sbin/apache2ctl -D FOREGROUND
;user=www-data
priority=300
stopasgroup=true
killasgroup=true

[program:djangomigrations]
command=/bin/bash -c "sleep 5;/usr/bin/python3 manage.py migrate"
directory=/var/www/vfw
user=www-data
autorestart=false
priority=400
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
