[program:postgresql]
command=/usr/lib/postgresql/9.5/bin/postgres -D /etc/postgresql/9.5/main
directory=/usr/lib/postgresql
user=postgres
stopsignal=INT

[program:renderd]
command=/bin/bash -c "until pg_isready -d gis; do sleep 1; done; \
                      renderd -f -c /usr/local/etc/renderd.conf"
directory=/var/lib/mod_tile
user=renderd

[program:apache]
command=/usr/sbin/apache2ctl -D FOREGROUND
;user=www-data
stopasgroup=true
killasgroup=true

[program:djangomigrations]
command=/bin/bash -c "until pg_isready -d vforwater; do sleep 1; done; \
                      python3 manage.py migrate"
directory=/var/www/vfw
user=www-data
startsecs=0
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:tilemill]
command=/bin/bash -c "tileoven/index.js"
directory=/home/tilemill
user=tilemill
environment=HOME="/home/tilemill",USER="tilemill"
