# Generated by Django 2.0.1 on 2018-01-23 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
