# Generated by Django 2.0.1 on 2018-06-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgresowner',
            name='psql_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postgresowner',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postgresreader',
            name='psql_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postgresreader',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
