# Generated by Django 2.0.1 on 2018-01-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationManagement', '0003_auto_20180125_1450'),
        ('AuthorizationManagement', '0002_auto_20180123_1426'),
    ]

    operations = [
    ]
