# Generated by Django 2.0 on 2018-01-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationManagement', '0004_merge_20180125_1830'),
        ('AuthorizationManagement', '0005_auto_20180125_1707'),
    ]

    operations = [
    ]
