# Generated by Django 2.0 on 2018-01-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationManagement', '0006_merge_20180126_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='description',
            field=models.CharField(default='default_description', max_length=250),
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='description',
            field=models.CharField(default='default_description', max_length=250),
        ),
    ]
