# Generated by Django 2.0.1 on 2018-02-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationManagement', '0011_auto_20180204_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='deletionrequest',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(default='MyResource', max_length=150),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(default='txt, pdf, url, etc.', max_length=50),
        ),
    ]
