# Generated by Django 2.0.1 on 2018-02-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationManagement', '0012_auto_20180204_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
