# Generated by Django 2.0 on 2018-03-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationManagement', '0014_auto_20180205_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='deletionrequest',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
