# Generated by Django 2.0 on 2018-03-04 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationManagement', '0015_auto_20180304_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
