# Generated by Django 2.0 on 2018-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationManagement', '0018_auto_20180304_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(error_messages={'max_length': 'Please specify a type within 50 chars'}, max_length=50),
        ),
    ]
