# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebProcessingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('endpoint', models.CharField(max_length=1024)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Web Processing Service',
                'verbose_name_plural': 'Web Processing Services',
            },
        ),
    ]
