# Generated by Django 2.0.1 on 2018-06-11 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('0', 'INPUT'), ('1', 'OUTPUT')], max_length=1)),
                ('format', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artefact',
                'verbose_name_plural': 'Artefacts',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Edge',
                'verbose_name_plural': 'Edges',
            },
        ),
        migrations.CreateModel(
            name='InputOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('0', 'INPUT'), ('1', 'OUTPUT')], max_length=1)),
                ('identifier', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(default='Add your super descriptive text here...', null=True, verbose_name='Descriptive text')),
                ('datatype', models.CharField(choices=[('0', 'LITERAL'), ('1', 'COMPLEX'), ('2', 'BOUNDING_BOX')], max_length=1, null=True)),
                ('format', models.CharField(max_length=200, null=True)),
                ('min_occurs', models.IntegerField()),
                ('max_occurs', models.IntegerField()),
            ],
            options={
                'verbose_name': 'InputOutput',
                'verbose_name_plural': 'InputOutputs',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(default='Add your super descriptive text here...', verbose_name='Descriptive text')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='de', max_length=3)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=0, max_digits=5)),
                ('y', models.DecimalField(decimal_places=0, max_digits=5)),
                ('status', models.CharField(choices=[('0', 'NONE'), ('1', 'READY'), ('2', 'WAITING'), ('3', 'RUNNING'), ('4', 'FINISHED'), ('5', 'FAILED'), ('6', 'DEPRECATED')], max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(default='Add your super descriptive text here...', verbose_name='Descriptive text')),
                ('status_url', models.URLField(max_length=1000)),
                ('started_at', models.DateTimeField(null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps_workflow.Process')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='Add your super descriptive text here...', verbose_name='Descriptive text')),
                ('percent_done', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to=settings.AUTH_USER_MODEL)),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
        migrations.CreateModel(
            name='WPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(default='Add your super descriptive text here...', verbose_name='Descriptive text')),
                ('capabilities_url', models.URLField(max_length=1000)),
                ('describe_url', models.URLField(max_length=1000)),
                ('execute_url', models.URLField(max_length=1000)),
            ],
            options={
                'verbose_name': 'WPS',
                'verbose_name_plural': 'WPS',
            },
        ),
        migrations.CreateModel(
            name='WPSProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=200)),
                ('provider_site', models.URLField(max_length=1000)),
                ('individual_name', models.CharField(max_length=200)),
                ('position_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'WPSProvider',
                'verbose_name_plural': 'WPSProviders',
            },
        ),
        migrations.AddField(
            model_name='wps',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps_workflow.WPSProvider'),
        ),
        migrations.AddField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps_workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='session',
            name='last_workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wps_workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='process',
            name='wps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps_workflow.WPS'),
        ),
        migrations.AddField(
            model_name='inputoutput',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps_workflow.Process'),
        ),
        migrations.AddField(
            model_name='edge',
            name='from_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_task', to='wps_workflow.Task'),
        ),
        migrations.AddField(
            model_name='edge',
            name='input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input', to='wps_workflow.InputOutput'),
        ),
        migrations.AddField(
            model_name='edge',
            name='output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wps_workflow.InputOutput'),
        ),
        migrations.AddField(
            model_name='edge',
            name='to_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps_workflow.Task'),
        ),
        migrations.AddField(
            model_name='edge',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps_workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wps_workflow.InputOutput'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps_workflow.Task'),
        ),
    ]
