"""
Django settings for heron project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Generate secret on initial run. ("random" should be replaced with "secrets" for python >=3.6)
import random, string

secretFile = os.path.join(os.path.expanduser('~'), '.django_secret.txt')
if not os.path.isfile(secretFile):
    SECRET_KEY = ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(64))
    with open(secretFile, 'w+') as f:
        f.write(SECRET_KEY)
else:
    with open(secretFile) as f:
        SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'vfwheron.apps.VfwheronConfig',
    'dashboard.apps.DashboardConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'heron_wps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'heron.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'heron.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'django.db',
    },
    'vforwater': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'vforwater',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# Default URLs for user authentication
LOGIN_URL = 'vfwheron:login'
LOGIN_REDIRECT_URL = 'vfwheron:home'
LOGOUT_REDIRECT_URL = 'vfwheron:home'

# LDAP authentication configuration
AUTHENTICATION_BACKENDS = (
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

import ldap
from django_auth_ldap.config import LDAPSearch, PosixGroupType

AUTH_LDAP_SERVER_URI = "ldap://bwidm.scc.kit.edu"

AUTH_LDAP_BIND_DN = "uid=fileservice-read,ou=admin,ou=sdmac,dc=bwlsdf,dc=de"
AUTH_LDAP_BIND_PASSWORD = "gk3gEniHdyWSerb" # TODO: hide/remove this information from repo
AUTH_LDAP_USER_SEARCH = LDAPSearch("ou=sdmac,dc=bwlsdf,dc=de",
                                   ldap.SCOPE_SUBTREE, "(uid=%(user)s)")

AUTH_LDAP_START_TLS = True

# Definition of LDAP group is required for AUTH_LDAP_USER_FLAGS_BY_GROUP.
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("ou=groups,ou=sdmac,dc=bwlsdf,dc=de",
    ldap.SCOPE_SUBTREE, "(objectClass=groupOfNames)"
)
AUTH_LDAP_GROUP_TYPE = PosixGroupType()

# Map some basic information from LDAP to the Django user.
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name":  "sn",
    "email":      "mail",
}

# I found some groups on bwidm which should be fine to map with these simple privileges right now.
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active":    ["cn=sdmac-vforwater,ou=groups,ou=sdmac,dc=bwlsdf,dc=de"],
    "is_staff":     ["cn=sdmac-vforwater,ou=groups,ou=sdmac,dc=bwlsdf,dc=de"],
    "is_superuser": ["cn=sdmac-vforwater-admin,ou=groups,ou=sdmac,dc=bwlsdf,dc=de"],
}

# Logging for LDAP
#import logging
#logger = logging.getLogger('django_auth_ldap')
#logger.addHandler(logging.StreamHandler())
#logger.setLevel(logging.DEBUG)
