@startuml
title Draw on the Map for a selection

hide footbox


== click on Button to open draw menu ==
[-> vfw.js ++: vfw.map.func.DrawOnMapMenu
note left: vfw.map.func.toggleDrawFilter()
vfw.js -> vfw.js: vfw.map.func.toggleDrawFilter()
note left: create interactions (draw, drawSquare, ...)\n add interactions (draw, drawSquare, ...)\n add styles,\n add controles for draw options

== click on draw square button ==
vfw.js -> vfw.js ++: vfw.map.control.drawSquare.on('drawstart')
vfw.js -> vfw.js: vfw.map.source.selectionSource.clear
vfw.js -> vfw.js ++: selectStartFun()
vfw.js -> vfw.js: set vfw.map.vars.selectionEdgeCoords
note left: Draw square on map (1st click).
return changes of geometry
'deactivate vfw.js

vfw.js -> vfw.js ++: vfw.map.control.drawSquare.on('drawend')
note left: Drawing ends with 2nd click on map.
vfw.js -> vfw.js: vfw.map.func.getSelectionEdgeCoords()
vfw.js -> vfw.js ++: vfw.html.getQuickSelection('draw')
vfw.js -[#blue]> vfw.js: vfw.url.updateFilterURL()
note right #aqua: TODO: URL should show only one draw option.
group ajax
vfw.js -> views.py ++: QuickFilterResults.get()
opt if 'draw'
    views.py -> views.py: create polygon
    else 'catchStartID'
    views.py -> delineator.py ++: delineate()
    delineator.py -> views.py --: polygon
    else 'catchout'
    opt if coords
        views.py -> views.py: create polygon
    else
    views.py -> delineator.py ++: delineate()
    delineator.py -> views.py --: polygon
    end
end
views.py -> views.py: create geoserver layer
end
return selection, results, layerIDs, dataIDs, dataExt
vfw.js -> menu_objects.js ++: vfw.map.updateMapSelection
menu_objects.js -> menu_objects.js: update zoomToExt
menu_objects.js -> menu_objects.js: update layer names
menu_objects.js -> menu_objects.js: update QuickMenu obj
menu_objects.js -> menu_objects.js: refresh data on map
return
vfw.js -> vfw.js: update sum in menu
vfw.js -> vfw.js: create store button if sum(results)<100
return (back to 'drawend')
vfw.js -> vfw.js: vfw.map.func.getSelectionEdgeCoords()[0][0]
vfw.js -> vfw.js: vfw.map.func.removeDrawInteractions()
note right: remove interaction for draw, modify, drawSquare, drawCatchmentOuthlet
vfw.js -> vfw.js: vfw.map.func.toggleDrawBackground()
deactivate
deactivate
deactivate





@enduml
-----------------------------------------------------------------------
