@startuml

participant vfw.js
participant menu_objects.js
title Make a selection online in the menu

hide footbox


== click on option in menu ==
' actor user #lightblue
[-> vfw.js ++: itemButtonFunction
vfw.js -> vfw.js: vfw.html.getQuickSelection
vfw.js -> vfw.js: vfw.url.getFilterURL
group ajax
vfw.js -> views.py ++: QuickFilterResults
loop selection Dictionary to build django filter (query)
    opt simple_query: get values
    else date: get start and end date
    else if_FAIR: get only available data
    else draw: get data intersecting the polygon
    end
end
views.py -> views.py: create query
opt has query
    views.py -> views.py: get entry extent
    opt use entry extent
    else get spatial extent
        opt use spatial extent
        else get geometry extent
            opt use geometry extent
            end
        end
    end
end
views.py -> views.py: collect IDs
views.py -> geoserver_layer.py: create_layer
geoserver_layer.py -> geoserver_layer.py ++: __build_layer_xml
opt point
else areal_data
else filtercatchment
else merit_catchment_coarse
else merit_catchment
else merit_river
else merit_river_simple
else
end
geoserver_layer.py -> geoserver_layer.py: __create_attributes
geoserver_layer.py -> geoserver: create layer in geoserver
geoserver_layer.py -> views.py --:
views.py -> vfw.js --: JSON(selection, #total, layer_name, dataExt, IDs)
vfw.js -> menu_objects.js ++: vfw.map.updateMapSelection
menu_objects.js -> menu_objects.js: vfw.map.control.zoomToExt.extent
menu_objects.js -> menu_objects.js: vfw.var.DATA_LAYER_NAME
menu_objects.js -> vfw.js: vfw.var.obj.selectedIds.quickMenu, set quickMenuIds
menu_objects.js -> menu_objects.js --: vfw.map.source.wfsPointSource.refresh
menu_objects.js -> vfw.js
vfw.js -> vfw.js: update #total string
opt "#total<100": show select all button
end



@enduml
-----------------------------------------------------------------------
