# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 15:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='LtDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=65)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'lt_domain',
            },
        ),
        migrations.CreateModel(
            name='LtLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_abbrev', models.CharField(max_length=20)),
                ('license_name', models.CharField(max_length=255)),
                ('legal_text', models.TextField(blank=True, null=True)),
                ('text_url', models.CharField(blank=True, max_length=255, null=True)),
                ('access', models.BooleanField()),
                ('share', models.BooleanField()),
                ('edit', models.BooleanField()),
                ('commercial', models.BooleanField()),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'lt_license',
            },
        ),
        migrations.CreateModel(
            name='LtLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroid_x', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('centroid_y', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geometry_type', models.CharField(blank=True, max_length=15, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'lt_location',
            },
        ),
        migrations.CreateModel(
            name='LtProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=65, unique=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'lt_project',
            },
        ),
        migrations.CreateModel(
            name='LtQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(max_length=25)),
                ('flag_weight', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'lt_quality',
            },
        ),
        migrations.CreateModel(
            name='LtSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=65, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('rel_height', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('orientation_degree', models.IntegerField(blank=True, null=True)),
                ('slope', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('landuse', models.CharField(blank=True, max_length=65, null=True)),
                ('site_comment', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'lt_site',
            },
        ),
        migrations.CreateModel(
            name='LtSoil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geology', models.CharField(blank=True, max_length=65, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=65, null=True)),
                ('porosity', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('field_capacity', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('residual_moisture', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'lt_soil',
            },
        ),
        migrations.CreateModel(
            name='LtSourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=65, unique=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'lt_source_type',
            },
        ),
        migrations.CreateModel(
            name='LtUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=65, unique=True)),
                ('unit_abbrev', models.CharField(max_length=15)),
                ('unit_symbol', models.CharField(max_length=5)),
                ('derived_si', models.NullBooleanField()),
                ('to_derived_si', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'lt_unit',
            },
        ),
        migrations.CreateModel(
            name='LtUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_institution', models.BooleanField()),
                ('first_name', models.CharField(blank=True, max_length=65, null=True)),
                ('last_name', models.CharField(blank=True, max_length=65, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'lt_user',
            },
        ),
        migrations.CreateModel(
            name='NmMetaDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'nm_meta_domain',
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.TextField(blank=True, null=True)),
                ('proj4text', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'spatial_ref_sys',
            },
        ),
        migrations.CreateModel(
            name='TblData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstamp', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_data',
            },
        ),
        migrations.CreateModel(
            name='TblDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.TextField()),
                ('settings', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_data_source',
            },
        ),
        migrations.CreateModel(
            name='TblMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_start', models.DateTimeField(blank=True, null=True)),
                ('ts_stop', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('support', models.CharField(blank=True, max_length=255, null=True)),
                ('spacing', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_meta',
            },
        ),
        migrations.CreateModel(
            name='TblSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(blank=True, max_length=65, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('documentation_url', models.TextField(blank=True, null=True)),
                ('last_configured', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('sensor_comment', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_sensor',
            },
        ),
        migrations.CreateModel(
            name='TblVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=65, unique=True)),
                ('variable_abbrev', models.CharField(max_length=15)),
                ('variable_symbol', models.CharField(max_length=5)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_variable',
            },
        ),
        migrations.CreateModel(
            name='Basiseinzugsgebiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langname', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('objectid', models.BigIntegerField()),
                ('object_id', models.FloatField()),
                ('fg_id', models.BigIntegerField()),
                ('fgkz_nr', models.FloatField(verbose_name='flussgebietskennzahl')),
                ('einzugsgeb', models.IntegerField(verbose_name='einzugsgebietsordnung')),
                ('einzugsg00', models.CharField(max_length=80, verbose_name='einzugsgebietsordnung in Worten')),
                ('einzugsg01', models.CharField(max_length=1)),
                ('einzugsg02', models.CharField(max_length=26)),
                ('vor_fgkz_n', models.FloatField(verbose_name='flussgebietskennzahl des vorfluters')),
                ('vor_fg_id', models.FloatField()),
                ('vor_fg_lan', models.CharField(max_length=100, verbose_name='vorfluter_langname')),
                ('wasserkoer', models.CharField(max_length=10, verbose_name='wasserkoerper_code')),
                ('wasserko00', models.CharField(max_length=85, verbose_name='wasserkoerper_name')),
                ('aenderungs', models.CharField(max_length=20)),
                ('aenderun00', models.CharField(max_length=20)),
                ('length', models.FloatField()),
                ('mod_by', models.CharField(max_length=32)),
                ('last_mod', models.CharField(max_length=20)),
                ('se_anno_ca', models.CharField(max_length=254)),
                ('wasserko01', models.BigIntegerField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=31467)),
            ],
        ),
    ]
