# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 15:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('val', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cluster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LtAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=65, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.BooleanField()),
                ('email', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('institution_department', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lt_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LtInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'lt_institution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LtLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=20)),
                ('full_name', models.TextField()),
                ('license_text', models.TextField(blank=True, null=True)),
                ('license_url', models.TextField(blank=True, null=True)),
                ('access', models.BooleanField()),
                ('share', models.BooleanField()),
                ('edit', models.BooleanField()),
                ('commercial', models.BooleanField()),
            ],
            options={
                'db_table': 'lt_license',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LtSourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, max_length=24, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mime', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lt_source_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LtUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('abbrev', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=10)),
                ('si_base', models.CharField(blank=True, max_length=255, null=True)),
                ('si', models.BooleanField()),
            ],
            options={
                'db_table': 'lt_unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NmCoreAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nm_core_additional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.TextField(blank=True, null=True)),
                ('proj4text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=60)),
                ('meta_value_str', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_value_real', models.FloatField(blank=True, null=True)),
                ('meta_value_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_additional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_start', models.DateTimeField(blank=True, null=True)),
                ('ts_stop', models.DateTimeField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('data_dimension', models.CharField(blank=True, max_length=3, null=True)),
                ('external_id', models.IntegerField(blank=True, null=True)),
                ('identifier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_core',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('geom_local', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'tbl_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('abbrev', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_variable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dim1D',
            fields=[
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vfwheron.TblCore')),
            ],
            options={
                'db_table': 'dim_1d',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTs',
            fields=[
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vfwheron.TblCore')),
                ('spacing_in_sec', models.IntegerField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('relative_height', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_ts',
                'managed': False,
            },
        ),
    ]
