# Generated by Django 2.2.16 on 2020-10-06 11:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('args', models.TextField(blank=True, null=True)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, db_column='lastUpdate', null=True)),
                ('encoding', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'datasources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasourceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datasource_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datatypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datatypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('stem', models.CharField(max_length=20)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('external_id', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=0)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
                ('version', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('embargo', models.BooleanField()),
                ('embargo_end', models.DateTimeField(blank=True, null=True)),
                ('publication', models.DateTimeField(blank=True, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, db_column='lastUpdate', null=True)),
                ('is_partial', models.BooleanField()),
                ('uuid', models.CharField(max_length=36)),
                ('citation', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrygroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=36)),
                ('publication', models.DateTimeField(blank=True, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, db_column='lastUpdate', null=True)),
            ],
            options={
                'db_table': 'entrygroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntrygroupTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'entrygroup_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
                ('uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('full_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keywords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=40)),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('by_attribution', models.BooleanField()),
                ('share_alike', models.BooleanField()),
                ('commercial_use', models.BooleanField()),
            ],
            options={
                'db_table': 'licenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=0)),
            ],
            options={
                'db_table': 'entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstamp', models.DateTimeField()),
                ('code', models.IntegerField()),
                ('description', models.TextField()),
                ('migration_head', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('affiliation', models.CharField(blank=True, max_length=1024, null=True)),
                ('organisation_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('attribution', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'persons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialScales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.IntegerField()),
                ('extent', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('support', models.DecimalField(decimal_places=999, max_digits=999)),
            ],
            options={
                'db_table': 'spatial_scales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemporalScales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.TextField()),
                ('observation_start', models.DateTimeField()),
                ('observation_end', models.DateTimeField()),
                ('support', models.DecimalField(decimal_places=999, max_digits=999)),
            ],
            options={
                'db_table': 'temporal_scales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thesaurus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('title', models.TextField()),
                ('organisation', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'thesaurus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=12)),
                ('si', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'variables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Generic1DData',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vfwheron.Entries')),
                ('index', models.DecimalField(decimal_places=999, max_digits=999)),
                ('value', models.DecimalField(decimal_places=999, max_digits=999)),
                ('precision', models.DecimalField(blank=True, decimal_places=999, max_digits=999, null=True)),
            ],
            options={
                'db_table': 'generic_1d_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Generic2DData',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vfwheron.Entries')),
                ('index', models.DecimalField(decimal_places=999, max_digits=999)),
                ('value1', models.DecimalField(decimal_places=999, max_digits=999)),
                ('value2', models.DecimalField(decimal_places=999, max_digits=999)),
                ('precision1', models.DecimalField(blank=True, decimal_places=999, max_digits=999, null=True)),
                ('precision2', models.DecimalField(blank=True, decimal_places=999, max_digits=999, null=True)),
            ],
            options={
                'db_table': 'generic_2d_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenericGeometryData',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vfwheron.Entries')),
                ('index', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0)),
                ('srid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geneic_geometry_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeomTimeseries',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vfwheron.Entries')),
                ('tstamp', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0)),
                ('srid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geom_timeseries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NmEntrygroups',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vfwheron.Entries')),
            ],
            options={
                'db_table': 'nm_entrygroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NmKeywordsEntries',
            fields=[
                ('keyword', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vfwheron.Keywords')),
            ],
            options={
                'db_table': 'nm_keywords_entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NmPersonsEntries',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vfwheron.Persons')),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'nm_persons_entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeseries',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vfwheron.Entries')),
                ('tstamp', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=999, max_digits=999)),
                ('precision', models.DecimalField(blank=True, decimal_places=999, max_digits=999, null=True)),
            ],
            options={
                'db_table': 'timeseries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeseries2D',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vfwheron.Entries')),
                ('tstamp', models.DateTimeField()),
                ('value1', models.DecimalField(decimal_places=999, max_digits=999)),
                ('value2', models.DecimalField(decimal_places=999, max_digits=999)),
                ('precision1', models.DecimalField(blank=True, decimal_places=999, max_digits=999, null=True)),
                ('precision2', models.DecimalField(blank=True, decimal_places=999, max_digits=999, null=True)),
            ],
            options={
                'db_table': 'timeseries_2d',
                'managed': False,
            },
        ),
    ]
