# Generated by Django 2.2.5 on 2019-09-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfwheron', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basiseinzugsgebiet',
            options={'managed': False},
        ),
    ]
