# Generated by Django 2.2.5 on 2019-10-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfwheron', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
